name: tierrating
services:

  server:
    build: .
    restart: unless-stopped
    ports:
      - 8080
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: tierrating
      DB_PASSWORD: testingPW
      ANILIST_CLIENT_KEY: 27404
      ANILIST_CLIENT_SECRET: xIEtzpqYI7jXaWJ4wuB4UKcGlWankJNeqXLIWsro
      ANILIST_REDIRECT_URL: http://localhost:3000/auth/anilist
      TRAKT_CLIENT_KEY: 271129879907506896d543ce9469f48f89cc0f839faf3e11c29e7ced0608bf4e
      TRAKT_CLIENT_SECRET: xIEtzpqYI7jXaWJ4wuB4UKcGlWankJNeqXLIWsro
      TRAKT_REDIRECT_URL: http://localhost:3000/auth/anilist

  ui:
    build: ../tierrating-ui
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      API_URL: 'http://server:8080'

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432
    volumes:
      - ./temp-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: tierrating
      POSTGRES_PASSWORD: testingPW
